server:
  profiles:
    active: default

  port: 8080

spring:
  application:
    name: jsf-with-spring

  jpa:
    generate-ddl: true

  datasource:
    url: jdbc:postgresql://localhost:5432/jsfwithspring?useSSL=false
    username: postgres
    password: "root"
    driver-class-name: org.postgresql.Driver